### ISSUE TITLE
Got a 500 error on a like % query

### ISSUE THREAD

**Issue by simonw** [simonw/django-sql-dashboard#41]
I tried this:
```sql
select * from reporter where auth0_role_name like '%Trainee%'
```
And got a 500 error. Should have had an inline pink error instead. The problem was that those `%` needed to be `%%` - should have a hint about that.

**Comment by simonw** [comment]
This was a problem with the new code for extracting named parameters:
```
Traceback (most recent call last):
  File "/Users/simon/.local/share/virtualenvs/vial-YGecuKOB/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/Users/simon/.local/share/virtualenvs/vial-YGecuKOB/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/simon/.local/share/virtualenvs/vial-YGecuKOB/lib/python3.9/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/simon/Dropbox/Development/django-sql-dashboard/django_sql_dashboard/views.py", line 45, in dashboard_index
    return _dashboard_index(request, sql_queries, title="Django SQL Dashboard")
  File "/Users/simon/Dropbox/Development/django-sql-dashboard/django_sql_dashboard/views.py", line 72, in _dashboard_index
    for p in extract_named_parameters(sql):
  File "/Users/simon/Dropbox/Development/django-sql-dashboard/django_sql_dashboard/utils.py", line 47, in extract_named_parameters
    sql % capture

Exception Type: ValueError at /dashboard/
Exception Value: unsupported format character ''' (0x27) at index 21
```
https://github.com/simonw/django-sql-dashboard/blob/fe9f0ce774ba5d3cb75e196879fd371c218c6783/django_sql_dashboard/utils.py#L45-L48
